title: Shivangi Vashi
email: vashi.s@northeastern.edu
description: Shivangi Vashi Personal Website
baseurl: "https://shivangiv.github.io"
localhost: 4000
mainhost: "http://localhost:4000"
url: shivangivashi.co

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: "assets/images/projects/"
    values:
      image: true
sass:
    sass_dir: _sass
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title:output_ext
